#!/bin/sh
#
# @name Quad-Rover Hybrid (Native Config)
#
# @type VTOL Quadrotor
# @class VTOL
#
# @maintainer YourName <your.email@example.com>
#

set VEHICLE_TYPE hybrid
param set-default MAV_TYPE 22

# Navigation and Sensors
param set-default NAV_ACC_RAD 2
param set-default NAV_LOITER_RAD 2
param set-default MIS_TAKEOFF_ALT 0.01
param set-default RTL_RETURN_ALT 30
param set-default RTL_DESCEND_ALT 10
param set-default EKF2_RNG_FOG 1.0
param set-default EKF2_MAG_TYPE 1

# Control Allocator Frontend Config (For QGC UI)
param set-default CA_AIRFRAME 2

# Force QGC to display 6 motor sliders for testing
param set-default CA_ROTOR_COUNT 6
param set-default CA_ROTOR0_PX 1
param set-default CA_ROTOR0_PY 1
param set-default CA_ROTOR1_PX -1
param set-default CA_ROTOR1_PY -1
param set-default CA_ROTOR2_PX 1
param set-default CA_ROTOR2_PY -1
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -1
param set-default CA_ROTOR3_PY 1
param set-default CA_ROTOR3_KM -0.05

# Additional Servos for Transformation
param set-default CA_SV_CS_COUNT 2

# Custom Parameters
param set-default HYBRID_TRANS_T 2.0
param set-default HYBRID_MAX_Z 0.5
