#!/bin/sh
#
# @name Quad-Rover Hybrid (Native Config)
#
# @type VTOL Quadrotor
# @class VTOL
#
# @maintainer YourName <your.email@example.com>
#

set VEHICLE_TYPE hybrid
param set-default MAV_TYPE 22

# Navigation and Sensors
param set-default NAV_ACC_RAD 2
param set-default NAV_LOITER_RAD 2
param set-default MIS_TAKEOFF_ALT 0.01
param set-default RTL_RETURN_ALT 30
param set-default RTL_DESCEND_ALT 10
param set-default EKF2_RNG_FOG 1.0
param set-default EKF2_MAG_TYPE 1

# Control Allocator Frontend Config (For QGC UI)
param set-default CA_AIRFRAME 2

# Quad motors remain on M1-M4. M5/M6 are unused because the wheels use CAN.
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 0
param set-default PWM_MAIN_FUNC6 0
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 1
param set-default CA_ROTOR0_PY 1
param set-default CA_ROTOR1_PX -1
param set-default CA_ROTOR1_PY -1
param set-default CA_ROTOR2_PX 1
param set-default CA_ROTOR2_PY -1
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -1
param set-default CA_ROTOR3_PY 1
param set-default CA_ROTOR3_KM -0.05

# Transformation servo on M8. A zero disarmed/failsafe value disables pulses.
param set-default PWM_MAIN_FUNC8 201
param set-default PWM_MAIN_DIS8 0
param set-default PWM_MAIN_FAIL8 0
param set-default CA_SV_CS_COUNT 1

# CAN1 has one runtime owner. Changing ownership parameters requires a reboot.
param set-default UAVCAN_ENABLE 0
param set-default -s CYPHAL_ENABLE 0
param set-default M2K_EN 1
param set-default M2K_L_ID 1
param set-default M2K_R_ID 2
param set-default M2K_MAX_RPM 18000
param set-default M2K_RPM_SLEW 18000
param set-default M2K_CUR_LIM 10000

# Bench calibration is required before driving can be armed.
param set-default M2K_SPD_P 0
param set-default M2K_SPD_I 0
param set-default M2K_SPD_D 0
param set-default M2K_SPD_FF 0
param set-default RO_MAX_THR_SPEED 2.47
param set-default HYB_SENS_EN 1
param set-default HYB_SV_QUD 0
param set-default HYB_SV_ROV 0

# Custom Parameters
param set-default HYBRID_TRANS_T 2.0
